### ISSUE TITLE
Player Moving Fast

### ISSUE THREAD

**Issue by communityus** [noirhero/ActionFramework#1]
Great example! Possibly the best Unity DOTS example I have seen.

Only problem I have is the player is moving too fast. The FPS is awesome 1000 fps. But when I try to jump over the barrels and then the tree afterwards it is too hard because he is zooming around way to fast. By the time I hit SPACE to jump he is already at the barrels.

**Comment by Kim-Hyunjung** [comment]
fixed! thx :)
